### PR TITLE
Refactor FontStyle type

### LINKED ISSUE #69: Add `FontStyle` enum

### PR DESCRIPTION
**Pull request by vyorkin**
* Make it a sum-type rather than newtype
* Extract `FontStyle`-related things into a separate module
* Add some tests for main use-cases

Resolves #69

### CODE REVIEW

**Comment by garyb** [comment]
Looks good 👍 unfortunately this and every other PR you open are conflicting after merging the selector fixes.

**Comment by vyorkin** [comment]
no problem let's merge them one by one, I'll rebase after each merge :)

**Comment by garyb** [comment]
Sounds good! Looking back on them all, I only have those couple of minor comments I made... but also some of the enumerable additions could be reworked in the same style as this now, if you don't mind?

**Comment by vyorkin** [comment]
Rebased, should be ready to merge

**Pull request merged**
