### PR TITLE
Use purescript-colors, fixes #22

### LINKED ISSUE #22: Problems with Color module
Excerpt from the current `CSS.Color` module:
``` purs
-data Color = Rgba Int Int Int Int		
-           | Hsla Number Number Number Number		
-           | Other Value		
-		
-instance isStringColor :: IsString Color where		
-  fromString = Other <<< fromString		
-		
-instance valColor :: Val Color where		
-  value (Rgba r g b 255) = Value <<< fromString $ "rgb(" <> intercalate ", " [show r, show g, show b] <> ")"		
-  value (Rgba r g b a) = Value <<< fromString $ "rgba(" <> intercalate ", " [show r, show g, show b, show a] <> ")"		
-  value (Hsla h s l 1.0) = Value <<< fromString $ "hsl(" <> intercalate ", " [show h, show s, show l] <> ")"		
-  value (Hsla h s l a) = Value <<< fromString $ "hsla(" <> intercalate ", " [show h, show s, show l, show a] <> ")"		
-  value (Other v) = v		
```

I think there are a few problems with this:
- The alpha value in RGBA colors should be a `Number` and the values should go from 0.0 to 1.0 (instead of 0 to 255).
- Saturation and lightness in HSL colors have to be defined as a percentage in CSS, for example: `hsl(120, 100%, 50%)`.

Consequently, RGBA, HSL and HSLA are not working right now (only RGB).

### PR DESCRIPTION
**Pull request by sharkdp**
**First off:** I'm totally fine if this get's closed... I have no idea if this is in line with the goals of purescript-css.

This PR essentially removes the existing color functionality and uses the [purescript-colors](https://github.com/sharkdp/purescript-colors) module instead.

**Changes:**
- Use the `Color` type from purescript-colors. Using `rgb` still works as before. All CSS color names are also still supported through [`Color.Scheme.X11`](https://pursuit.purescript.org/packages/purescript-colors/0.4.3/docs/Color.Scheme.X11). This change allows users to profit from the color-creation and manipulation functionality of purescript-colors.
- Fixes #22 in that it allows colors to be specified as RGBA, HSL, HSLA (and many additional ways).
- Use [`Color.Scale`](https://pursuit.purescript.org/packages/purescript-colors/0.4.3/docs/Color.Scale) for `linearGradient`. This allows to create gradients in different color spaces, for example.
- Fixed `Site` example module
- Requires PureScript 0.8

**Simple example:** 
``` purs
-- Define a base brand color
let baseColor = MaterialDesign.indigo

-- Automatically choose a text color (white or black) for the header
fromString "#header" ? do
  backgroundColor baseColor
  color (textColor baseColor)

-- Choose a lighter variant for the page background
body ? do
  backgroundColor (lighten 0.3 baseColor)
```

### CODE REVIEW

**Comment by zudov** [comment]
:+1: When I first saw `purescript-colors` I thought that it would be nice to use it in `purescript-css`.

**Comment by puffnfresh** [comment]
:+1:

**Comment by jdegoes** [comment]
:+1:  Looks like a great fit. We are ordinarily a little hesitant to have a `slamdata` repo depend on something that's not in `slamdata`, PureScript core, or PureScript contrib. But I think it makes sense.

**Comment by sharkdp** [comment]
> We are ordinarily a little hesitant to have a slamdata repo depend on something that's not in slamdata, PureScript core, or PureScript contrib.

That's a reasonable concern, of course. So far, purescript-colors is probably only used by me. I believe it has a good test coverage, but some some real-world usage wouldn't hurt ;-)

Is purescript-css used in some projects? Is it still actively developed?

**Comment by jdegoes** [comment]
Yes, it's used in halogen and actively maintained. @garyb Any final comments? Lots of thumbs up so far. :smile:

**Comment by garyb** [comment]
I'm good with using `purescript-colours` :+1:

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
