### PR TITLE
Fixed NEL import; Fixed Number/Int issues; Builds Now

### PR DESCRIPTION
**Pull request by born2defy**
Hey there,

I was experimenting with this library and had to revise a few minor things to get the Site module to build with the latest version of the purescript compiler.  Specifically I had to change the original import of Data.Array.NonEmpty to Data.NonEmpty, I had to break out the foreign imports into their own js module, and I had to add a bunch of .0's to change many of the ints to numbers.  I'm not sure if this is useful to you or not, but since it is done I thought I would share it in case that it is.

Thank you for the excellent library.  I am not a professional developer so please excuse me if I am not handling this correctly as this is literally the first pull request I have ever initiated.

### CODE REVIEW

**Comment by puffnfresh** [comment]
:+1:

**Comment by garyb** [comment]
Great, thanks!

**Comment by jdegoes** [comment]
Thanks @born2defy! And welcome to the wonderful world of open source. :smiley: 

Awesome first pull request. :+1:

**Comment by born2defy** [comment]
Thank you!  I hope to try and contribute more as I am very grateful for the work you guys (and others) have done with this incredible language.

**Pull request merged**
