### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by zudov**

### CODE REVIEW

**Comment by zudov** [comment]
Hmm. travis failure looks quite strange.

**Comment by zudov** [comment]
Works fine for me with `pulp`.

But in travis build, it doesn't error on `import Control.Monad.Writer.Class (tell)`, but then fails with a message "Unknown value 'tell'".

**Comment by zudov** [comment]
Restarted it just to make sure.

**Comment by zudov** [comment]
It also builds fine locally with `gulp`

**Comment by zudov** [comment]
So, could it be some problem with purescript's binary (mine is compiled from source)?

I don't have any better guesses.

**Comment by garyb** [comment]
Travis is fetching an old version of the compiler - you could take that out and add an npm dependency instead. While you're there, can you bump `gulp-purescript` to `^0.7.0` too please.

**Comment by zudov** [comment]
Passed \o/

@garyb Thanks for help with this

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
